/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/bryant/HackRPI2014/roomba_workspace/src/roomba_node/srv/CreateMessage.srv
 *
 */


#ifndef ROOMBA_NODE_MESSAGE_CREATEMESSAGE_H
#define ROOMBA_NODE_MESSAGE_CREATEMESSAGE_H

#include <ros/service_traits.h>


#include <roomba_node/CreateMessageRequest.h>
#include <roomba_node/CreateMessageResponse.h>


namespace roomba_node
{

struct CreateMessage
{

typedef CreateMessageRequest Request;
typedef CreateMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CreateMessage
} // namespace roomba_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roomba_node::CreateMessage > {
  static const char* value()
  {
    return "88917c848e1bff8f91d4008c0ad38390";
  }

  static const char* value(const ::roomba_node::CreateMessage&) { return value(); }
};

template<>
struct DataType< ::roomba_node::CreateMessage > {
  static const char* value()
  {
    return "roomba_node/CreateMessage";
  }

  static const char* value(const ::roomba_node::CreateMessage&) { return value(); }
};


// service_traits::MD5Sum< ::roomba_node::CreateMessageRequest> should match 
// service_traits::MD5Sum< ::roomba_node::CreateMessage > 
template<>
struct MD5Sum< ::roomba_node::CreateMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roomba_node::CreateMessage >::value();
  }
  static const char* value(const ::roomba_node::CreateMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roomba_node::CreateMessageRequest> should match 
// service_traits::DataType< ::roomba_node::CreateMessage > 
template<>
struct DataType< ::roomba_node::CreateMessageRequest>
{
  static const char* value()
  {
    return DataType< ::roomba_node::CreateMessage >::value();
  }
  static const char* value(const ::roomba_node::CreateMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roomba_node::CreateMessageResponse> should match 
// service_traits::MD5Sum< ::roomba_node::CreateMessage > 
template<>
struct MD5Sum< ::roomba_node::CreateMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roomba_node::CreateMessage >::value();
  }
  static const char* value(const ::roomba_node::CreateMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roomba_node::CreateMessageResponse> should match 
// service_traits::DataType< ::roomba_node::CreateMessage > 
template<>
struct DataType< ::roomba_node::CreateMessageResponse>
{
  static const char* value()
  {
    return DataType< ::roomba_node::CreateMessage >::value();
  }
  static const char* value(const ::roomba_node::CreateMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROOMBA_NODE_MESSAGE_CREATEMESSAGE_H
