/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/bryant/HackRPI2014/roomba_workspace/src/roomba_node/srv/CreateMessage.srv
 *
 */


#ifndef ROOMBA_NODE_MESSAGE_CREATEMESSAGEREQUEST_H
#define ROOMBA_NODE_MESSAGE_CREATEMESSAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roomba_node
{
template <class ContainerAllocator>
struct CreateMessageRequest_
{
  typedef CreateMessageRequest_<ContainerAllocator> Type;

  CreateMessageRequest_()
    : command()
    , argument1(0.0)
    , argument2(0.0)
    , argument3(0.0)
    , argument4(0.0)  {
    }
  CreateMessageRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , argument1(0.0)
    , argument2(0.0)
    , argument3(0.0)
    , argument4(0.0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef double _argument1_type;
  _argument1_type argument1;

   typedef double _argument2_type;
  _argument2_type argument2;

   typedef double _argument3_type;
  _argument3_type argument3;

   typedef double _argument4_type;
  _argument4_type argument4;




  typedef boost::shared_ptr< ::roomba_node::CreateMessageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roomba_node::CreateMessageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CreateMessageRequest_

typedef ::roomba_node::CreateMessageRequest_<std::allocator<void> > CreateMessageRequest;

typedef boost::shared_ptr< ::roomba_node::CreateMessageRequest > CreateMessageRequestPtr;
typedef boost::shared_ptr< ::roomba_node::CreateMessageRequest const> CreateMessageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roomba_node::CreateMessageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roomba_node::CreateMessageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roomba_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roomba_node::CreateMessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roomba_node::CreateMessageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roomba_node::CreateMessageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roomba_node::CreateMessageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roomba_node::CreateMessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roomba_node::CreateMessageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roomba_node::CreateMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1f96dd5b54236744db9b8d26e18041d";
  }

  static const char* value(const ::roomba_node::CreateMessageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1f96dd5b5423674ULL;
  static const uint64_t static_value2 = 0x4db9b8d26e18041dULL;
};

template<class ContainerAllocator>
struct DataType< ::roomba_node::CreateMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roomba_node/CreateMessageRequest";
  }

  static const char* value(const ::roomba_node::CreateMessageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roomba_node::CreateMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n\
float64 argument1\n\
float64 argument2\n\
float64 argument3\n\
float64 argument4\n\
";
  }

  static const char* value(const ::roomba_node::CreateMessageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roomba_node::CreateMessageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.argument1);
      stream.next(m.argument2);
      stream.next(m.argument3);
      stream.next(m.argument4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CreateMessageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roomba_node::CreateMessageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roomba_node::CreateMessageRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "argument1: ";
    Printer<double>::stream(s, indent + "  ", v.argument1);
    s << indent << "argument2: ";
    Printer<double>::stream(s, indent + "  ", v.argument2);
    s << indent << "argument3: ";
    Printer<double>::stream(s, indent + "  ", v.argument3);
    s << indent << "argument4: ";
    Printer<double>::stream(s, indent + "  ", v.argument4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROOMBA_NODE_MESSAGE_CREATEMESSAGEREQUEST_H
