(cl:defpackage roomba_node-srv
  (:use )
  (:export
   "ARDUINOMESSAGE"
   "<ARDUINOMESSAGE-REQUEST>"
   "ARDUINOMESSAGE-REQUEST"
   "<ARDUINOMESSAGE-RESPONSE>"
   "ARDUINOMESSAGE-RESPONSE"
   "CREATEMESSAGE"
   "<CREATEMESSAGE-REQUEST>"
   "CREATEMESSAGE-REQUEST"
   "<CREATEMESSAGE-RESPONSE>"
   "CREATEMESSAGE-RESPONSE"
  ))

